import "server-only";

import { prisma } from "@/lib/db";
import type { Participant } from "@prisma/client";
import type { CurrentAccount } from "@/lib/account/auth";
import { issueBadgeCredential } from "@/lib/badge";
import { BadgeError } from "@/lib/badge/errors";
import { audit } from "@/lib/admin/audit";

// Shared server helpers for the new role-based registration flows.
//
// Every role flow (Visitor / Speaker / Sponsor / Partner / Content Creator)
// funnels through the same three steps:
//   1. ensureParticipantForAccount — reuse or create the Participant tied
//      to the AccountUser for the current event. Never duplicates.
//   2. ensureActiveBadge — eagerly issue a BadgeCredential if the
//      participant does not yet have one. Idempotent + race-safe.
//   3. Role-specific business logic (Application creation, participation
//      choice, etc.) — belongs to the caller.
//
// This module is intentionally small. All decisions about *which* fields
// to write on the Participant + *which* Application to create belong to
// the role-specific server action.

export type EnsureResult =
  | { kind: "ready"; participant: Participant }
  | { kind: "conflict" }
  | { kind: "no-event" };

/**
 * Reuse the AccountUser's existing Participant (matched by
 * `accountUserId`) or create a fresh one. Never matches on email alone
 * (that would let a malicious signup hijack a legacy anonymous
 * Participant — the claim flow in `lib/account/email-verification.ts`
 * is the only path that binds an anonymous Participant to an
 * AccountUser, and only after email-ownership proof).
 *
 * Race-safe: if two concurrent requests both try to bootstrap the
 * Participant, the DB `@@unique([eventId, email])` catches the loser
 * and we re-fetch by `accountUserId`.
 */
export async function ensureParticipantForAccount(
  account: CurrentAccount
): Promise<EnsureResult> {
  const event = await prisma.event.findFirst({ orderBy: { startsAt: "asc" } });
  if (!event) return { kind: "no-event" };

  const existing = await prisma.participant.findFirst({
    where: { eventId: event.id, accountUserId: account.id }
  });
  if (existing) return { kind: "ready", participant: existing };

  try {
    const created = await prisma.participant.create({
      data: {
        eventId: event.id,
        accountUserId: account.id,
        firstName: account.firstName,
        lastName: account.lastName,
        email: account.email,
        phone: null,
        country: "Algérie",
        registrationType: "ATTENDEE",
        status: "REGISTERED",
        profile: "VISITOR"
      }
    });
    return { kind: "ready", participant: created };
  } catch (err) {
    if (
      typeof err === "object" &&
      err !== null &&
      "code" in err &&
      (err as { code?: string }).code === "P2002"
    ) {
      // Either a concurrent request from the same AccountUser just created
      // the Participant (safe to re-fetch) or an anonymous Participant
      // already claims this (eventId, email) pair. The anonymous case is
      // the "conflict" surface — the claim flow handles binding.
      const raced = await prisma.participant.findFirst({
        where: { eventId: event.id, accountUserId: account.id }
      });
      if (raced) return { kind: "ready", participant: raced };
      return { kind: "conflict" };
    }
    throw err;
  }
}

/**
 * Ensure the Participant has an ACTIVE BadgeCredential. Idempotent — if
 * one already exists we return the existing id and skip issuance. Errors
 * are swallowed and logged: badge issuance must NEVER be the reason a
 * registration action fails from the attendee's point of view (they can
 * always retry from /compte/badge, which rotates on demand).
 *
 * SECURITY: the raw token generated by issueBadgeCredential is
 * deliberately discarded here. The attendee retrieves their QR by
 * rotating at /compte/badge, which is auth-gated and mints a fresh raw
 * token that only exists inside the QR image pixels.
 */
export async function ensureActiveBadge(participantId: string): Promise<void> {
  const existing = await prisma.badgeCredential.findFirst({
    where: { participantId, status: "ACTIVE" },
    select: { id: true }
  });
  if (existing) return;

  try {
    await issueBadgeCredential(participantId);
  } catch (err) {
    if (err instanceof BadgeError && err.code === "ACTIVE_EXISTS") {
      // Concurrent issue won the race — nothing to do.
      return;
    }
    // Non-fatal: audit and swallow. The attendee can generate the badge
    // from /compte/badge on demand.
    // eslint-disable-next-line no-console
    console.warn(
      "[register] ensureActiveBadge failed (non-fatal):",
      err instanceof Error ? err.message : err
    );
    await audit({
      action: "badge.issue.failed",
      entity: "Participant",
      entityId: participantId,
      meta: { reason: err instanceof Error ? err.message : String(err) }
    }).catch(() => undefined);
  }
}
